### ISSUE TITLE
Cannot create new user

### ISSUE THREAD

**Issue by MatthewCYLau** [gauravjot/social-network#9]
I got Postgres error when creating new user

`ERROR:  relation "account_person" does not exist at character 402`

`STATEMENT:  SELECT "account_person"."id", "account_person"."first_name", "account_person"."last_name", "account_person"."email", "account_person"."password", "account_person"."avatar", "account_person"."birthday", "account_person"."tagline", "account_person"."slug", "account_person"."hometown", "account_person"."work", "account_person"."cover_image", "account_person"."created", "account_person"."updated" FROM "account_person" WHERE "account_person"."email" = 'hello@world.com' LIMIT 21`

**Comment by gauravjot** [comment]
Did you migrate the database tables? There is `.envsample` file which you need to rename to `.env` and fill out your database details.

**Comment by MatthewCYLau** [comment]
I was using `docker-compose.yml` to spin-up a `postgres` image. Did you download the PostgreSQL server from its official site?

**Comment by gauravjot** [comment]
Yes, its official PostgreSQL. Your error states that table does not exist
which can only happen if migration from django wasn't successful. Let me
know if you get it working.

**Comment by jgx0** [comment]
I get `no changes detected` after running the migration. I get the same error.
